version: '3.3'
services:
  wrapper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mapotempo/router-wrapper:${MAPOTEMPO_VERSION:-56.0.1}
    ports:
      - "127.0.0.1:8082:80" # HOST:CONTAINER, edit only HOST part
    volumes:
      - ./production.rb:/srv/app/config/environments/production.rb
      - ./production.rb:/srv/app/config/environments/development.rb
      - ./poly:/srv/app/poly
    restart: always
    links:
      - redis-cache
    environment:
      APP_ENV: production # Switch to "development" for more traces

  otp-bordeaux:
    build:
      context: otp
      args:
        OTP_VERSION: 1.2.0
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: bordeaux
    ports:
      - "7001:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-nantes:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: nantes
    ports:
      - "7002:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-toulouse:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: toulouse
    ports:
      - "7003:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-metz:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: metz
    ports:
      - "7004:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-nancy:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: nancy
    ports:
      - "7005:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-rennes:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: rennes
    ports:
      - "7006:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-strasbourg:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: strasbourg
    ports:
      - "7007:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-idf:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: idf
    ports:
      - "7008:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-grenoble:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: grenoble
    ports:
      - "7009:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-marseille:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: marseille
    ports:
      - "7010:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-nice:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: nice
    ports:
      - "7011:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-brest:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: brest
    ports:
      - "7012:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-poitiers:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: poitiers
    ports:
      - "7013:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-lille:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: lille
    ports:
      - "7014:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-besancon:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: besancon
    ports:
      - "7015:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  otp-la-roche-sur-yon:
    image: mapotempo/otp-server:1.2.0
    environment:
      GRAPH: la-roche-sur-yon
    ports:
      - "7016:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  osrm-car-overseas:
    build:
      context: osrm/server
    image: mapotempo/osrm-server:${OSRM_VERSION:-5.12.0-mt1}
    environment:
      BASENAME: car-overseas
      NODE_CONFIG: "{ \"maxspeed\": 104 }"
    ports:
      - "5006:5000"
      - "6006:1723"
    volumes:
      - ./osrm/data:/srv/osrm/data
      - /dev/log:/dev/log
    restart: always

  osrm-car-europe:
    build:
      context: osrm/server
    image: mapotempo/osrm-server:${OSRM_VERSION:-5.12.0-mt1}
    environment:
      BASENAME: car-europe
      NODE_CONFIG: "{ \"maxspeed\": 104 }"
    ports:
      - "5005:5000"
      - "6005:1723"
    volumes:
      - ./osrm/data:/srv/osrm/data
      - /dev/log:/dev/log
    restart: always

  osrm-car-france-distance:
    build:
      context: osrm/server
    image: mapotempo/osrm-server:${OSRM_VERSION:-5.12.0-mt1}
    environment:
      BASENAME: car-france-distance
      NODE_CONFIG: "{ \"maxspeed\": 3.6 }"
    ports:
      - "5004:5000"
      - "6004:1723"
    volumes:
      - ./osrm/data:/srv/osrm/data
      - /dev/log:/dev/log
    restart: always

  osrm-car-interurban-israel-and-palestine:
    build:
      context: osrm/server
    image: mapotempo/osrm-server:${OSRM_VERSION:-5.12.0-mt1}
    environment:
      BASENAME: car-interurban-israel-and-palestine
      NODE_CONFIG: "{ \"maxspeed\": 104 }"
    ports:
      - "5008:5000"
      - "6008:1723"
    volumes:
      - ./osrm/data:/srv/osrm/data
      - /dev/log:/dev/log
    restart: always

  osrm-truck-medium-france:
    build:
      context: osrm/server
    image: mapotempo/osrm-server:${OSRM_VERSION:-5.12.0-mt1}
    environment:
      BASENAME: truck_medium-france
      NODE_CONFIG: "{ \"maxspeed\": 104 }"
    ports:
      - "5007:5000"
      - "6007:1723"
    volumes:
      - ./osrm/data:/srv/osrm/data
      - /dev/log:/dev/log
    restart: always

  osrm-foot-france:
    build:
      context: osrm/server
    image: mapotempo/osrm-server:${OSRM_VERSION:-5.12.0-mt1}
    environment:
      BASENAME: foot-france
      NODE_CONFIG: "{ \"maxspeed\": 5 }"
    ports:
      - "5002:5000"
      - "6002:1723"
    volumes:
      - ./osrm/data:/srv/osrm/data
      - /dev/log:/dev/log
    restart: always

  osrm-bicycle-france:
    build:
      context: osrm/server
    image: mapotempo/osrm-server:${OSRM_VERSION:-5.12.0-mt1}
    environment:
      BASENAME: bicycle-france
      NODE_CONFIG: "{ \"maxspeed\": 15 }"
    ports:
      - "5001:5000"
      - "6001:1723"
    volumes:
      - ./osrm/data:/srv/osrm/data
      - /dev/log:/dev/log
    restart: always

  redis-cache:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    command: redis-server --save ""
    restart: always
